export interface Flashcard {
  id: string;
  type: 'basic' | 'cloze';
  front?: string; // For basic cards
  back?: string; // For basic cards
  text?: string; // For cloze cards
  clozes?: number[]; // Positions of cloze deletions
  tags: string[];
  deckId: string;
  folderId?: string; // NEW: Folder association
  source: 'auto' | 'manual' | 'imported';
  sourceFile?: string;
  createdAt: Date;
  lastReviewed?: Date;
  reviewCount: number;
}

export interface Deck {
  id: string;
  name: string;
  description: string;
  cardCount: number;
  autoGenerated: number;
  imported: number;
  manual: number;
  color: string;
  folderId?: string; // NEW: Folder association
  createdAt: Date;
}

// NEW: Folder interface
export interface Folder {
  id: string;
  name: string;
  parentId: string | null; // null for root folders
  color?: string;
  icon?: string;
  deckCount: number;
  cardCount: number;
  isExpanded: boolean;
  createdAt: Date;
  children?: Folder[]; // For tree structure
}

export type ViewMode = 'decks' | 'upload' | 'generating' | 'review-cards' | 'edit-card' | 'study' | 'import' | 'export';

export interface ExportSettings {
  includeScheduling: boolean;
  cardType: 'all' | 'basic' | 'cloze';
}

// NEW: Folder action types
export type FolderAction = 'create' | 'rename' | 'delete' | 'move' | 'color';

// NEW: Folder sort options
export type FolderSortBy = 'name' | 'date' | 'items';