import { Deck, Flashcard } from '../types';

// NEW: Import Folder type
import type { Folder } from '../types';

// NEW: Sample folder hierarchy
export const initialFolders: Folder[] = [
  {
    id: 'folder-root-1',
    name: 'Internal Medicine',
    parentId: null,
    color: '#3B82F6',
    deckCount: 2,
    cardCount: 283,
    isExpanded: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'folder-cardio',
    name: 'Cardiology',
    parentId: 'folder-root-1',
    color: '#EF4444',
    deckCount: 1,
    cardCount: 127,
    isExpanded: false,
    createdAt: new Date('2024-01-05'),
  },
  {
    id: 'folder-pulm',
    name: 'Pulmonology',
    parentId: 'folder-root-1',
    color: '#06B6D4',
    deckCount: 1,
    cardCount: 156,
    isExpanded: false,
    createdAt: new Date('2024-01-06'),
  },
  {
    id: 'folder-root-2',
    name: 'Pharmacology',
    parentId: null,
    color: '#8B5CF6',
    deckCount: 1,
    cardCount: 243,
    isExpanded: true,
    createdAt: new Date('2024-01-02'),
  },
  {
    id: 'folder-cardio-drugs',
    name: 'Cardiovascular Drugs',
    parentId: 'folder-root-2',
    color: '#EC4899',
    deckCount: 1,
    cardCount: 89,
    isExpanded: false,
    createdAt: new Date('2024-01-10'),
  },
  {
    id: 'folder-antibiotics',
    name: 'Antibiotics',
    parentId: 'folder-root-2',
    color: '#10B981',
    deckCount: 0,
    cardCount: 0,
    isExpanded: false,
    createdAt: new Date('2024-01-11'),
  },
  {
    id: 'folder-root-3',
    name: 'Step 2 CK Review',
    parentId: null,
    color: '#F59E0B',
    deckCount: 0,
    cardCount: 0,
    isExpanded: false,
    createdAt: new Date('2024-01-03'),
  },
];

export const initialDecks: Deck[] = [
  {
    id: 'deck1',
    name: 'Cardiology',
    description: 'Cardiovascular system flashcards',
    cardCount: 127,
    autoGenerated: 85,
    imported: 32,
    manual: 10,
    color: '#EF4444',
    folderId: 'folder-cardio', // NEW: Associated with folder
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'deck2',
    name: 'Pharmacology',
    description: 'Drug mechanisms and interactions',
    cardCount: 243,
    autoGenerated: 150,
    imported: 80,
    manual: 13,
    color: '#8B5CF6',
    folderId: 'folder-root-2', // NEW: Associated with folder
    createdAt: new Date('2024-01-10'),
  },
  {
    id: 'deck3',
    name: 'Pathology',
    description: 'Disease mechanisms',
    cardCount: 156,
    autoGenerated: 120,
    imported: 30,
    manual: 6,
    color: '#10B981',
    folderId: 'folder-pulm', // NEW: Associated with folder
    createdAt: new Date('2024-01-05'),
  },
];

export const sampleCards: Flashcard[] = [
  {
    id: 'card1',
    type: 'basic',
    front: 'What is the primary pacemaker of the heart?',
    back: 'The SA (sinoatrial) node is the primary pacemaker, located in the right atrium.',
    tags: ['Cardiology', 'Anatomy'],
    deckId: 'deck1',
    folderId: 'folder-cardio', // NEW: Associated with folder
    source: 'auto',
    sourceFile: 'cardio-lecture-01.pdf',
    createdAt: new Date(),
    reviewCount: 5,
  },
  {
    id: 'card2',
    type: 'cloze',
    text: 'The {{c1::SA node}} is the primary pacemaker of the heart, firing at {{c2::60-100}} bpm.',
    tags: ['Cardiology', 'Physiology'],
    deckId: 'deck1',
    folderId: 'folder-cardio', // NEW: Associated with folder
    source: 'auto',
    sourceFile: 'cardio-lecture-01.pdf',
    createdAt: new Date(),
    reviewCount: 3,
  },
  {
    id: 'card3',
    type: 'basic',
    front: 'What are the absolute contraindications for beta-blockers in ACS?',
    back: 'Cardiogenic shock, decompensated heart failure, high-degree AV block, severe bradycardia (HR <50 bpm)',
    tags: ['Cardiology', 'Pharmacology'],
    deckId: 'deck1',
    folderId: 'folder-cardio', // NEW: Associated with folder
    source: 'imported',
    createdAt: new Date(),
    reviewCount: 8,
  },
];