import { useState } from 'react';
import { Button } from '../../ui/button';
import { Input } from '../../ui/input';
import { Textarea } from '../../ui/textarea';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '../../ui/dialog';
import { toast } from 'sonner';
import { Deck } from '../types';

interface CreateDeckDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onCreateDeck: (deck: Deck) => void;
}

export function CreateDeckDialog({ open, onOpenChange, onCreateDeck }: CreateDeckDialogProps) {
  const [deckName, setDeckName] = useState('');
  const [deckDescription, setDeckDescription] = useState('');

  const handleCreate = () => {
    if (!deckName.trim()) {
      toast.error('Please enter a deck name');
      return;
    }

    const newDeck: Deck = {
      id: `deck-${Date.now()}`,
      name: deckName,
      description: deckDescription,
      cardCount: 0,
      autoGenerated: 0,
      imported: 0,
      manual: 0,
      color: '#3B82F6',
      createdAt: new Date(),
    };

    onCreateDeck(newDeck);
    toast.success(`Deck "${deckName}" created`);
    setDeckName('');
    setDeckDescription('');
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="bg-bg-secondary border-border-primary">
        <DialogHeader>
          <DialogTitle className="text-text-primary">Create New Deck</DialogTitle>
          <DialogDescription className="text-text-secondary">
            Create a new flashcard deck for your studies
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-4">
          <div>
            <label className="text-sm text-text-secondary mb-2 block">Deck Name</label>
            <Input
              value={deckName}
              onChange={(e) => setDeckName(e.target.value)}
              placeholder="e.g., Cardiology"
              className="bg-bg-tertiary border-border-primary text-text-primary"
            />
          </div>
          <div>
            <label className="text-sm text-text-secondary mb-2 block">Description</label>
            <Textarea
              value={deckDescription}
              onChange={(e) => setDeckDescription(e.target.value)}
              placeholder="Brief description of this deck..."
              className="bg-bg-tertiary border-border-primary text-text-primary resize-none"
              rows={3}
            />
          </div>
        </div>
        <DialogFooter>
          <Button
            variant="outline"
            onClick={() => {
              onOpenChange(false);
              setDeckName('');
              setDeckDescription('');
            }}
            className="border-border-primary text-text-primary hover:bg-bg-tertiary"
          >
            Cancel
          </Button>
          <Button
            onClick={handleCreate}
            disabled={!deckName.trim()}
            className="bg-blue-primary hover:bg-blue-hover text-white"
          >
            Create Deck
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
