import { Card } from '../../ui/card';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '../../ui/dropdown-menu';
import {
  MoreVertical,
  Edit2,
  Trash2,
  Upload,
  CreditCard,
  Sparkles,
  Download,
} from 'lucide-react';
import { toast } from 'sonner';
import { Deck } from '../types';

interface DeckCardProps {
  deck: Deck;
  onClick: () => void;
  onExport: () => void;
}

export function DeckCard({ deck, onClick, onExport }: DeckCardProps) {
  return (
    <Card
      className="bg-bg-secondary border-border-primary p-5 cursor-pointer hover:border-blue-primary/50 transition-colors group"
      onClick={onClick}
    >
      <div className="flex items-start justify-between mb-3">
        <div
          className="size-10 rounded-lg flex items-center justify-center"
          style={{ backgroundColor: `${deck.color}20` }}
        >
          <CreditCard className="size-5" style={{ color: deck.color }} />
        </div>
        <DropdownMenu>
          <DropdownMenuTrigger asChild onClick={(e) => e.stopPropagation()}>
            <button className="p-1 opacity-0 group-hover:opacity-100 hover:bg-bg-tertiary rounded">
              <MoreVertical className="size-4 text-text-tertiary" />
            </button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end" className="bg-bg-secondary border-border-primary">
            <DropdownMenuItem
              onClick={(e) => {
                e.stopPropagation();
                onExport();
              }}
              className="text-text-primary hover:bg-bg-tertiary cursor-pointer"
            >
              <Upload className="size-4 mr-2" />
              Export to Anki
            </DropdownMenuItem>
            <DropdownMenuItem
              onClick={(e) => {
                e.stopPropagation();
                toast.info('Edit feature coming soon');
              }}
              className="text-text-primary hover:bg-bg-tertiary cursor-pointer"
            >
              <Edit2 className="size-4 mr-2" />
              Edit Deck
            </DropdownMenuItem>
            <DropdownMenuSeparator className="bg-border-primary" />
            <DropdownMenuItem
              onClick={(e) => {
                e.stopPropagation();
                toast.error('Delete feature coming soon');
              }}
              className="text-red-500 hover:bg-red-500/10 cursor-pointer"
            >
              <Trash2 className="size-4 mr-2" />
              Delete
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>

      <h3 className="text-lg text-text-primary mb-1">{deck.name}</h3>
      <p className="text-xs text-text-secondary mb-4 line-clamp-2">{deck.description}</p>

      <div className="space-y-2">
        <div className="flex items-center justify-between text-sm">
          <span className="text-text-tertiary">Total Cards</span>
          <span className="text-text-primary font-medium">{deck.cardCount}</span>
        </div>
        <div className="flex items-center gap-4 text-xs text-text-tertiary">
          <span className="flex items-center gap-1">
            <Sparkles className="size-3" />
            {deck.autoGenerated} Auto
          </span>
          <span className="flex items-center gap-1">
            <Download className="size-3" />
            {deck.imported} Imported
          </span>
          <span className="flex items-center gap-1">
            <Edit2 className="size-3" />
            {deck.manual} Manual
          </span>
        </div>
      </div>
    </Card>
  );
}
